define([], function() {
  return {
    "MoveToFolderCommand": "Move to folder",
    "DialogTitle": "Move page to folder",
    "CurrentFolderLabel": "Current folder",
    "AvailableFoldersLabel": "Available folders",
    "AvailableFoldersHint": "Browse the full Site Pages hierarchy below and choose any destination folder, including Site Pages.",
    "SelectedFolderLabel": "Destination folder",
    "SelectedSiteLabel": "Destination site",
    "NoFolderSelectedLabel": "Select a destination folder",
    "CancelButton": "Cancel",
    "MoveButton": "Move",
    "MovingButton": "Moving...",
    "MovingStatusLabel": "Moving '{0}'",
    "LoadingFoldersLabel": "Loading folders...",
    "EmptyFolderMessage": "No folders are available in Site Pages.",
    "SearchFoldersPlaceholder": "Search folders",
    "NoMatchingFoldersMessage": "No folders match your search.",
    "SameFolderMessage": "Select a different destination. The page is already in that folder.",
    "LoadFoldersError": "We couldn't load the Site Pages folders.",
    "MovePageError": "We couldn't move the page.",
    "SitePagesRootLabel": "Site Pages",
    "ThisSiteLabel": "This site",
    "SearchSitesPlaceholder": "Search sites",
    "SearchSitesLabel": "Destination site",
    "NoMatchingSitesMessage": "No sites match your search.",
    "LoadSitesError": "We couldn't search sites.",
    "SitePagesLibraryMissingError": "The selected site does not have a Site Pages library.",
    "MetadataSectionLabel": "Metadata to copy",
    "MetadataSectionHint": "Choose which matching columns to copy to the destination page. Columns are matched by internal name.",
    "SelectAllMetadataLabel": "Select all",
    "ClearMetadataLabel": "Clear",
    "LoadingMetadataLabel": "Loading matching columns...",
    "NoMatchingMetadataMessage": "No matching writable columns were found between the source and destination Site Pages libraries.",
    "LoadMetadataError": "We couldn't load matching metadata columns.",
    "CrossSiteDeleteFailedError": "The page was copied to the destination, but we couldn't delete the source page. Remove the source page manually if needed."
  }
});
