define([], function() {
  return {
    "MoveToFolderCommand": "Move to folder",
    "DialogTitle": "Move page to folder",
    "DialogTitleMultiple": "Move pages to folder",
    "SelectedPagesLabel": "Selected pages",
    "SelectedPagesCountLabel": "{0} pages selected",
    "CurrentFolderLabel": "Current folder",
    "AvailableFoldersLabel": "Available folders",
    "AvailableFoldersHint": "Browse the full Site Pages hierarchy below and choose any destination folder, including Site Pages.",
    "SelectedFolderLabel": "Destination folder",
    "NoFolderSelectedLabel": "Select a destination folder",
    "CancelButton": "Cancel",
    "MoveButton": "Move",
    "MovingButton": "Moving...",
    "MovingStatusLabel": "Moving '{0}'",
    "LoadingFoldersLabel": "Loading folders...",
    "EmptyFolderMessage": "No folders are available in Site Pages.",
    "SearchFoldersPlaceholder": "Search folders",
    "NoMatchingFoldersMessage": "No folders match your search.",
    "SameFolderMessage": "Select a different destination. The page is already in that folder.",
    "SameFolderMessageMultiple": "Select a different destination. All selected pages are already in that folder.",
    "LoadFoldersError": "We couldn't load the Site Pages folders.",
    "MovePageError": "We couldn't move the page.",
    "MovePagesPartialError": "Moved {0} of {1} pages. Failed: {2}",
    "SitePagesRootLabel": "Site Pages",
    "DestinationSiteLabel": "Which site",
    "DestinationSitePlaceholder": "https://contoso.sharepoint.com/sites/destination",
    "LoadSiteButton": "Load Folders",
    "LoadSiteButtonAriaLabel": "Load folders for this site",
    "LoadingSiteLabel": "Loading folders...",
    "ConfirmSitePromptMessage": "Confirm the destination site, then click Load Folders to browse.",
    "InvalidSiteUrlMessage": "Enter a valid HTTPS SharePoint site URL.",
    "LoadSiteError": "We couldn't load that site or its Site Pages library.",
    "SiteNotFoundOrNoAccessMessage": "That site wasn't found or you don't have permission to access it. Check the URL and try again.",
    "CrossSiteMoveError": "We couldn't move the page to that site.",
    "CrossSiteAccessDeniedMessage": "SharePoint blocked moving this page to that site (often because Custom script is blocked on the destination). Allow custom script on the destination site, then try again."
  }
});
